# Generated by Django 5.2 on 2025-06-16 14:03

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import xaridorlar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xaridorlar', '0002_alter_xaridor_options_alter_xaridorhujjat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xaridor',
            options={'verbose_name': 'Xaridor', 'verbose_name_plural': 'Xaridorlar'},
        ),
        migrations.AlterModelOptions(
            name='xaridorhujjat',
            options={'verbose_name': 'Xaridor Hujjati', 'verbose_name_plural': 'Xaridor Hujjatlari'},
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan Sana'),
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='email',
            field=models.EmailField(blank=True, help_text='Masalan: example@domain.com', max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Manzili'),
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='hozirgi_balans',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hozirgi Balans'),
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='ism_familiya',
            field=models.CharField(max_length=100, verbose_name='Ism va Familiya'),
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='izoh',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='sana',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='telefon_raqam',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Masalan: +998901234567', max_length=128, null=True, region=None, verbose_name='Telefon Raqami'),
        ),
        migrations.AlterField(
            model_name='xaridorhujjat',
            name='hujjat',
            field=models.FileField(upload_to=xaridorlar.models.generate_unique_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx']), xaridorlar.models.validate_file_size], verbose_name='Hujjat Fayli'),
        ),
        migrations.AlterField(
            model_name='xaridorhujjat',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Asl Fayl Nomi'),
        ),
        migrations.AlterField(
            model_name='xaridorhujjat',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan Sana'),
        ),
        migrations.AlterField(
            model_name='xaridorhujjat',
            name='xaridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hujjatlar', to='xaridorlar.xaridor', verbose_name='Xaridor'),
        ),
    ]
