# Generated by Django 5.2 on 2025-06-29 21:46

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import xaridorlar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xaridorlar', '0003_alter_xaridor_options_alter_xaridorhujjat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xaridor',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='xaridorhujjat',
            options={'verbose_name': 'Customer Document', 'verbose_name_plural': 'Customer Documents'},
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='email',
            field=models.EmailField(blank=True, help_text='Example: example@domain.com', max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='hozirgi_balans',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='ism_familiya',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='izoh',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='sana',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='xaridor',
            name='telefon_raqam',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Example: +998901234567', max_length=128, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='xaridorhujjat',
            name='hujjat',
            field=models.FileField(upload_to=xaridorlar.models.generate_unique_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx']), xaridorlar.models.validate_file_size], verbose_name='Document File'),
        ),
        migrations.AlterField(
            model_name='xaridorhujjat',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Original File Name'),
        ),
        migrations.AlterField(
            model_name='xaridorhujjat',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded Date'),
        ),
        migrations.AlterField(
            model_name='xaridorhujjat',
            name='xaridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hujjatlar', to='xaridorlar.xaridor', verbose_name='Customer'),
        ),
    ]
