# Generated by Django 5.2 on 2025-06-29 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xaridorlar', '0005_alter_xaridor_options_alter_xaridorhujjat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xaridor',
            name='email',
            field=models.EmailField(blank=True, help_text='Masalan: example@domain.com', max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email Manzili Ascending'),
        ),
    ]
