# Generated by Django 5.2 on 2025-06-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bildirishnoma',
            name='days_left',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qoldiq kunlar'),
        ),
        migrations.AddField(
            model_name='bildirishnoma',
            name='days_overdue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kechikkan kunlar'),
        ),
    ]
