# Generated by Django 5.2 on 2025-06-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0002_bildirishnoma_days_left_bildirishnoma_days_overdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bildirishnoma',
            name='sms_sent',
        ),
        migrations.AddField(
            model_name='bildirishnoma',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email Yuborildi'),
        ),
        migrations.DeleteModel(
            name='SmsLog',
        ),
    ]
