# Generated by Django 5.2 on 2025-06-14 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0003_remove_bildirishnoma_sms_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Email mavzusi')),
                ('message', models.TextField(verbose_name='Email matni')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Qabul qiluvchi email')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana')),
                ('status', models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz')], default='success', max_length=20, verbose_name='Holati')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Xato xabari')),
                ('bildirishnoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_history', to='chiqim.bildirishnoma', verbose_name='Bildirishnoma')),
            ],
            options={
                'verbose_name': 'Email Tarixi',
                'verbose_name_plural': 'Email Tarixlari',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['sent_at'], name='chiqim_emai_sent_at_963c0b_idx'), models.Index(fields=['status'], name='chiqim_emai_status_aa6e98_idx')],
            },
        ),
    ]
