# Generated by Django 5.2 on 2025-06-16 14:18

import chiqim.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chiqim', '0004_emailhistory'),
        ('trucks', '0001_initial'),
        ('xaridorlar', '0003_alter_xaridor_options_alter_xaridorhujjat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bildirishnoma',
            options={'ordering': ['tolov_sana'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='boshlangichtolov',
            options={'verbose_name': 'Initial Payment', 'verbose_name_plural': 'Initial Payments'},
        ),
        migrations.AlterModelOptions(
            name='chiqim',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='emailhistory',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Email History', 'verbose_name_plural': 'Email Histories'},
        ),
        migrations.AlterModelOptions(
            name='tolovturi',
            options={'verbose_name': 'Monthly Payment', 'verbose_name_plural': 'Monthly Payments'},
        ),
        migrations.AddField(
            model_name='chiqim',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Original File Name'),
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='chiqim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirishnomalar', to='chiqim.chiqim', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='days_left',
            field=models.IntegerField(blank=True, null=True, verbose_name='Days Left'),
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='days_overdue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Days Overdue'),
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email Sent'),
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='eslatish_kunlari',
            field=models.PositiveIntegerField(default=30, verbose_name='Days Before Notification'),
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='eslatma',
            field=models.BooleanField(default=False, verbose_name='Notified'),
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='sana',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('urgent', 'Urgent'), ('warning', 'Warning')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bildirishnoma',
            name='tolov_sana',
            field=models.DateField(verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='boshlangichtolov',
            name='bank',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank Used for Payment'),
        ),
        migrations.AlterField(
            model_name='boshlangichtolov',
            name='chiqim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boshlangich_tolovlar', to='chiqim.chiqim', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='boshlangichtolov',
            name='firma_nomi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='boshlangichtolov',
            name='is_partial',
            field=models.BooleanField(default=False, verbose_name='Partial Payment'),
        ),
        migrations.AlterField(
            model_name='boshlangichtolov',
            name='izoh',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='boshlangichtolov',
            name='sana',
            field=models.DateField(verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='boshlangichtolov',
            name='summa',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Payment Amount'),
        ),
        migrations.AlterField(
            model_name='boshlangichtolov',
            name='tolov_turi',
            field=models.CharField(choices=[('zelle', 'Zelle'), ('wire_transfer', 'Wire Transfer'), ('cash', 'Cash'), ('button', 'Button')], max_length=20, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='boshlangichtolov',
            name='xaridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xaridorlar.xaridor', verbose_name='Buyer'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='bo_lib_tolov_muddat',
            field=models.PositiveIntegerField(default=0, verbose_name='Installment Period (Months)'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='boshlangich_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Initial Payment (Planned)'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='hujjatlar',
            field=models.FileField(blank=True, null=True, upload_to=chiqim.models.generate_unique_chiqim_filename, verbose_name='Documents'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='izoh',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='narx',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='oyiga_tolov',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monthly Payment'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='qoldiq_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Remaining Amount'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='sana',
            field=models.DateField(auto_now_add=True, verbose_name='Sale Date'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='tolov_sana',
            field=models.DateField(verbose_name='First Payment Date'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiqim', to='trucks.truck', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='chiqim',
            name='xaridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiqim', to='xaridorlar.xaridor', verbose_name='Buyer'),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='bildirishnoma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_history', to='chiqim.bildirishnoma', verbose_name='Notification'),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='message',
            field=models.TextField(verbose_name='Email Content'),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='recipient',
            field=models.EmailField(max_length=254, verbose_name='Recipient Email'),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sent Date'),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Email Subject'),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='bank',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank Used for Payment'),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='chiqim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='chiqim.chiqim', verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='firma_nomi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='is_partial',
            field=models.BooleanField(default=False, verbose_name='Partial Payment'),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='izoh',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='sana',
            field=models.DateField(verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='summa',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Payment Amount'),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='tolov_turi',
            field=models.CharField(choices=[('zelle', 'Zelle'), ('wire_transfer', 'Wire Transfer'), ('cash', 'Cash'), ('button', 'Button')], max_length=20, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='tolovturi',
            name='xaridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xaridorlar.xaridor', verbose_name='Buyer'),
        ),
    ]
