# Generated by Django 5.2 on 2025-06-16 06:33

import django.core.validators
import django.db.models.deletion
import qarz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarz', '0001_initial'),
        ('trucks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'To‘lov', 'verbose_name_plural': 'To‘lovlar'},
        ),
        migrations.AlterModelOptions(
            name='qarz',
            options={'ordering': ['-given_date'], 'verbose_name': 'Qarz', 'verbose_name_plural': 'Qarzlar'},
        ),
        migrations.AddField(
            model_name='qarz',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=qarz.models.qarz_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx']), qarz.models.validate_file_size], verbose_name='Hujjat'),
        ),
        migrations.AddField(
            model_name='qarz',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Asl fayl nomi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='To‘lov summasi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(verbose_name='To‘lov sanasi'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='qarz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='qarz.qarz', verbose_name='Qarz'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Qarz summasi'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='borrower_name',
            field=models.CharField(max_length=100, verbose_name='Qarz oluvchi ismi'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='given_date',
            field=models.DateField(auto_now_add=True, verbose_name='Qarz berilgan sana'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='To‘langanmi?'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_loans', to=settings.AUTH_USER_MODEL, verbose_name='Qarz beruvchi'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='To‘lov muddati'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Qoldiq summa'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='trucks.truck', verbose_name='Yuk mashinasi'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['qarz'], name='qarz_paymen_qarz_id_09a7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='qarz_paymen_payment_e6d84f_idx'),
        ),
        migrations.AddIndex(
            model_name='qarz',
            index=models.Index(fields=['lender', 'is_paid'], name='qarz_qarz_lender__c7e6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='qarz',
            index=models.Index(fields=['given_date'], name='qarz_qarz_given_d_f0ac6f_idx'),
        ),
    ]
