# Generated by Django 5.2 on 2025-06-17 08:10

import django.core.validators
import django.db.models.deletion
import qarz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarz', '0002_alter_payment_options_alter_qarz_options_and_more'),
        ('trucks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='qarz',
            options={'ordering': ['-given_date'], 'verbose_name': 'Loan', 'verbose_name_plural': 'Loans'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Payment Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='qarz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='qarz.qarz', verbose_name='Loan'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Loan Amount'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='borrower_name',
            field=models.CharField(max_length=100, verbose_name='Borrower Name'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=qarz.models.qarz_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx']), qarz.models.validate_file_size], verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='given_date',
            field=models.DateField(auto_now_add=True, verbose_name='Loan Given Date'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid?'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_loans', to=settings.AUTH_USER_MODEL, verbose_name='Lender'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Original File Name'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Due Date'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Remaining Amount'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='trucks.truck', verbose_name='Truck'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
