# Generated by Django 5.2 on 2025-06-16 06:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import xarajatlar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
        ('xarajatlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xarajat',
            options={'ordering': ['-date'], 'verbose_name': 'Xarajat', 'verbose_name_plural': 'Xarajatlar'},
        ),
        migrations.AddField(
            model_name='xarajat',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Asl fayl nomi'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=xarajatlar.models.xarajat_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx']), xarajatlar.models.validate_file_size], verbose_name='Hujjat'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='expense_type',
            field=models.CharField(choices=[('repair', 'Tamirlash'), ('fuel', 'Yoqilg‘i'), ('insurance', 'Sug‘urta'), ('parts', 'Ehtiyot qismlar'), ('other', 'Boshqa')], max_length=50, verbose_name='Xarajat turi'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trucks.truck', verbose_name='Yuk mashinasi'),
        ),
        migrations.AddIndex(
            model_name='xarajat',
            index=models.Index(fields=['truck', 'expense_type'], name='xarajatlar__truck_i_27084c_idx'),
        ),
        migrations.AddIndex(
            model_name='xarajat',
            index=models.Index(fields=['date'], name='xarajatlar__date_627e1a_idx'),
        ),
    ]
