# Generated by Django 5.2 on 2025-06-16 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarajatlar', '0002_alter_xarajat_options_xarajat_original_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xarajat',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='expense_type',
            field=models.CharField(choices=[('repair', "Ta'mirlash"), ('fuel', 'Yoqilg‘i'), ('insurance', 'Sug‘urta'), ('parts', 'Ehtiyot qismlar'), ('other', 'Boshqa')], max_length=50, verbose_name='Xarajat turi'),
        ),
    ]
