# Generated by Django 5.2 on 2025-06-17 08:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import xarajatlar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
        ('xarajatlar', '0003_alter_xarajat_amount_alter_xarajat_expense_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xarajat',
            options={'ordering': ['-date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=xarajatlar.models.xarajat_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx']), xarajatlar.models.validate_file_size], verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='expense_type',
            field=models.CharField(choices=[('repair', 'Repair'), ('fuel', 'Fuel'), ('insurance', 'Insurance'), ('parts', 'Spare Parts'), ('other', 'Other')], max_length=50, verbose_name='Expense Type'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Original File Name'),
        ),
        migrations.AlterField(
            model_name='xarajat',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trucks.truck', verbose_name='Truck'),
        ),
    ]
